const actionTypes = {
    AUTH_CHECK_STATE: 'AUTH_CHECK_STATE',
    AUTH_USER: 'AUTH_USER',
    AUTH_START: 'AUTH_START',
    AUTH_REGISTER_START: 'AUTH_REGISTER_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    AUTH_CHECK_TIMEOUT: 'AUTH_CHECK_TIMEOUT',
    AUTH_INITIATE_LOGOUT: 'AUTH_INITIATE_LOGOUT',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    SET_AUTH_REDIRECT_PATH: 'SET_AUTH_REDIRECT_PATH'
};
export default actionTypes;